import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, test } from "node:test";

import { GRID, MARK_BODY, MARK_EYE, mascotCells, RESTING_POSE } from "./mascot-grid";

const ROOT = join(import.meta.dirname, "..", "..", "..");
const svg = readFileSync(join(ROOT, "public", "instela-mark.svg"), "utf8");
const css = readFileSync(join(ROOT, "src", "app", "globals.css"), "utf8");

/**
 * Read the filled cells back out of a generated path.
 *
 * The generator emits horizontal runs as `M{x} {y}h{n}v1H{x}z`. Matching that
 * shape is only safe if we also prove the whole `d` was consumed — otherwise a
 * hand-edit into some other path syntax would parse as zero cells and every
 * assertion below would pass vacuously against an empty set.
 */
function cellsFromPath(d: string): Set<string> {
  const RUN = /M(\d+) (\d+)h(\d+)v1H\1z/g;
  const out = new Set<string>();
  let consumed = 0;
  for (const m of d.matchAll(RUN)) {
    consumed += m[0].length;
    const x = Number(m[1]);
    const y = Number(m[2]);
    for (let i = 0; i < Number(m[3]); i++) out.add(`${x + i},${y}`);
  }
  assert.equal(consumed, d.length, "the whole path must parse as horizontal runs");
  return out;
}

function pathFor(fill: string): string {
  const m = svg.match(new RegExp(`fill="${fill}" d="([^"]*)"`, "i"));
  assert.ok(m, `public/instela-mark.svg has no path filled ${fill}`);
  return m[1];
}

/**
 * THE TAB MARK AND THE MARK IN THE NAV ARE ONE PICTURE.
 *
 * They were two, drawn separately, and they were not even the same character —
 * a student met one silhouette in the browser tab and a different one in the
 * header. `public/instela-mark.svg` is now generated by `npm run build:mark`
 * from the same grid `Mascot.tsx` renders, and this is what stops the two
 * drifting apart again: edit the grid without regenerating and this fails.
 */
describe("the published mark matches the grid the component renders", () => {
  const pose = mascotCells(RESTING_POSE.facing, RESTING_POSE.blink);
  const body = new Set(pose.filter((c) => !c.eye).map((c) => `${c.x},${c.y}`));
  const eye = new Set(pose.filter((c) => c.eye).map((c) => `${c.x},${c.y}`));

  test("every body cell, and no others", () => {
    assert.ok(body.size > 0);
    assert.deepEqual(cellsFromPath(pathFor(MARK_BODY)), body, "run `npm run build:mark`");
  });

  test("the eye cell, and no others", () => {
    assert.equal(eye.size, 1);
    assert.deepEqual(cellsFromPath(pathFor(MARK_EYE)), eye, "run `npm run build:mark`");
  });

  test("the viewBox is the grid, so the mark is not cropped or padded", () => {
    assert.match(svg, new RegExp(`viewBox="0 0 ${GRID} ${GRID}"`));
  });

  test("crispEdges, or the pixel art antialiases into mush at small sizes", () => {
    assert.match(svg, /shape-rendering="crispEdges"/);
  });

  /**
   * An SVG loaded as a favicon has no page to inherit CSS custom properties
   * from, so the mark carries literal hex where the component writes
   * `var(--accent)`. That is a second copy of a colour, and the only honest
   * way to hold it is to assert it against the stylesheet that defines it.
   */
  test("the literal hex still equals the accent tokens in globals.css", () => {
    assert.match(css, new RegExp(`--accent:\\s*${MARK_BODY};`, "i"));
    assert.match(css, new RegExp(`--accent-lite:\\s*${MARK_EYE};`, "i"));
  });
});

/**
 * The site shipped `create-next-app`'s Vercel triangle as its favicon from the
 * initial commit until 2026-08-24 — the default is a real file that Next's
 * `app/favicon.ico` convention serves whether or not anyone chose it, so
 * "we set metadata.icons" was not enough to displace it.
 */
describe("favicon.ico is ours", () => {
  const ico = readFileSync(join(ROOT, "src", "app", "favicon.ico"));

  test("is an icon directory of PNG payloads at the sizes browsers ask for", () => {
    assert.equal(ico.readUInt16LE(0), 0, "reserved");
    assert.equal(ico.readUInt16LE(2), 1, "type: icon");
    const count = ico.readUInt16LE(4);
    const sizes: number[] = [];
    for (let i = 0; i < count; i++) {
      const e = 6 + i * 16;
      sizes.push(ico[e] || 256);
      const off = ico.readUInt32LE(e + 12);
      assert.equal(
        ico.subarray(off, off + 4).toString("hex"),
        "89504e47",
        "each entry should be a PNG payload",
      );
    }
    assert.deepEqual(sizes, [16, 32, 48]);
  });

  test("is not the 25KB create-next-app default", () => {
    assert.ok(ico.length < 8000, `favicon.ico is ${ico.length} bytes — regenerated?`);
  });
});
