-- Pricing tiers — the entitlement seam plus the usage counter for
-- quantity-capped free tools that have no persisted artifact to count
-- (a resume critique and a GitHub audit are recomputed on every render,
-- unlike a cover letter or a tracked application, which already have a
-- real row per unit).
--
-- Generated by hand: `drizzle-kit generate` requires an interactive TTY to
-- resolve its rename-vs-add heuristic and this environment has none, the
-- same limitation 0015 and 0016 hit before it (see their absent
-- meta/<tag>_snapshot.json). No columns are dropped or renamed here, so
-- there is nothing to disambiguate — this is the exact SQL `generate` would
-- have produced.
--> statement-breakpoint

ALTER TABLE "profiles" ADD COLUMN "plan" text DEFAULT 'free' NOT NULL;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "plan_updated_at" timestamp with time zone;--> statement-breakpoint

CREATE TABLE "feature_usage" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"feature" text NOT NULL,
	"count" integer DEFAULT 0 NOT NULL,
	"last_key" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "feature_usage" ADD CONSTRAINT "feature_usage_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "feature_usage_user_feature_unique" ON "feature_usage" USING btree ("user_id","feature");--> statement-breakpoint

-- Hand-appended, same reasoning as 0011's listing_reports block: drizzle-kit
-- emits CREATE TABLE only, migration 0002 cannot cover a table created after
-- it, and PostgREST serves `anon`/`authenticated` to anyone holding the
-- public key. Without this, feature_usage would be world-readable — every
-- signed-in student's run counts against every gated tool, joined to their
-- user id.
--
-- The app connects as table owner and bypasses RLS (see CLAUDE.md's landmine
-- list), so this is defense-in-depth for the PostgREST door, not how the app
-- itself reads or writes this table. `authenticated` gets SELECT on its own
-- rows only, which is enough for a client to render "you have used your free
-- run" without a round trip through a Server Action if that is ever wanted.
-- INSERT/UPDATE are deliberately not granted: `src/lib/pricing/usage.ts` is
-- the only writer, and it runs server-side against the owner connection.

ALTER TABLE "feature_usage" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint

GRANT SELECT ON "feature_usage" TO authenticated;--> statement-breakpoint

DROP POLICY IF EXISTS "feature_usage_own" ON "feature_usage";--> statement-breakpoint
CREATE POLICY "feature_usage_own" ON "feature_usage" FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = "user_id");
